# Generated by Django 3.1.2 on 2020-10-09 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hdesk', '0002_carthridge'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='short_name',
            field=models.CharField(default='ОКО', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carthridge',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Отделение', to='hdesk.department'),
        ),
    ]
