# Generated by Django 3.1.2 on 2020-10-12 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hdesk', '0003_auto_20201009_1021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carthridge',
            new_name='Technics',
        ),
    ]
