# Generated by Django 3.1.2 on 2020-10-12 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hdesk', '0007_auto_20201012_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technics',
            options={'verbose_name': 'Техника', 'verbose_name_plural': 'Техника'},
        ),
        migrations.RemoveField(
            model_name='technics',
            name='depart',
        ),
        migrations.AlterField(
            model_name='sendrecord',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Отделение', to='hdesk.department'),
        ),
    ]
