# Generated by Django 3.1.2 on 2020-10-12 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hdesk', '0008_auto_20201012_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='technics',
            name='tec_type',
            field=models.ForeignKey(default='Нет', on_delete=django.db.models.deletion.CASCADE, related_name='Тип', to='hdesk.type'),
            preserve_default=False,
        ),
    ]
