# Generated by Django 3.1.2 on 2020-10-12 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hdesk', '0010_remove_technics_tec_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='technics',
            name='tec_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Тип', to='hdesk.type'),
            preserve_default=False,
        ),
    ]
