# Generated by Django 3.1.2 on 2020-10-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hdesk', '0011_technics_tec_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technics',
            name='tec_type',
        ),
    ]
