# Generated by Django 3.1.2 on 2020-10-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hdesk', '0012_remove_technics_tec_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendrecord',
            name='depart',
        ),
    ]
