# Generated by Django 3.1.2 on 2020-10-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hdesk', '0013_remove_sendrecord_depart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendrecord',
            name='technics',
        ),
    ]
