# Generated by Django 3.1.2 on 2020-10-12 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hdesk', '0015_auto_20201012_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technics',
            name='tec_type',
        ),
    ]
