# Generated by Django 3.1.2 on 2020-10-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdesk', '0019_technics_t_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='technics',
            name='writeoff',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
