# Generated by Django 3.1.2 on 2020-10-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdesk', '0020_technics_writeoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendrecord',
            name='filled',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
