# Generated by Django 3.1.2 on 2020-10-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hdesk', '0021_sendrecord_filled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendrecord',
            old_name='filled',
            new_name='done',
        ),
    ]
