# Generated by Django 3.1.2 on 2020-10-13 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hdesk', '0022_auto_20201013_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendrecord',
            name='depart',
        ),
        migrations.AddField(
            model_name='technics',
            name='depart',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Отделение', to='hdesk.department'),
        ),
    ]
