# Generated by Django 3.1.2 on 2020-10-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdesk', '0024_auto_20201013_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteOffTec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('depart', models.CharField(max_length=500)),
            ],
        ),
    ]
