# Generated by Django 3.1.2 on 2020-10-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdesk', '0025_writeofftec'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeofftec',
            name='date_woff',
            field=models.DateField(blank=True, default=None),
        ),
    ]
