# Generated by Django 3.1.2 on 2020-10-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdesk', '0026_writeofftec_date_woff'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendrecord',
            name='get_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sendrecord',
            name='send_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
