# Generated by Django 3.1.2 on 2020-10-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdesk', '0027_auto_20201013_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendrecord',
            name='retus_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
