# Generated by Django 3.1.2 on 2020-10-14 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hdesk', '0028_sendrecord_retus_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WriteOffTec',
        ),
        migrations.RemoveField(
            model_name='sendrecord',
            name='depart',
        ),
        migrations.AddField(
            model_name='technics',
            name='depart',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Отделение', to='hdesk.department'),
        ),
        migrations.AddField(
            model_name='technics',
            name='serial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technics',
            name='writeoff',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
